backend:
  name: github
  repo: yndajas/simple-website
  branch: main
  open_authoring: true
publish_mode: editorial_workflow
show_preview_links: true
media_folder: assets/images
collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: views/posts
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - {
          label: Date,
          name: date,
          widget: string,
          required: true,
          pattern:
            [
              '^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$',
              "Must be in the format YYYY-MM-DD",
            ],
        }
      - { label: Body, name: body, widget: markdown, required: true }
