backend:
  name: github
  repo: yndajas/simple-website
  branch: main
  open_authoring: true
publish_mode: editorial_workflow
show_preview_links: true
media_folder: assets/images
collections:
  - name: blog
    label: Blog
    label_singular: Blog page
    folder: views/blog
    create: true
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Date, name: date, widget: string, required: true }
      - { label: Body, name: body, widget: markdown, required: true }
