#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

CI=false

for ARG in "$@"
do
  case $ARG in
    --ci-environment)
      CI=true
      ;;
  esac
  shift
done

echo "==> Installing dependencies"

if [ "$CI" = true ]; then
  echo "==> Installing Node dependencies..."

  npm ci
else
  echo "==> Installing Node and fswatch if needed..."

  nodenv install --skip-existing
  brew bundle install

  echo "==> Installing Node dependencies..."

  npm install
fi
