#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

CI=false

for ARG in "$@"
do
  case $ARG in
    --ci-environment)
      CI=true
      ;;
  esac
  shift
done

echo "==> Installing dependencies"

if [ "$CI" = false ]; then
  echo "==> Installing Node and fswatch if needed..."
  nodenv install --skip-existing
  brew bundle install
fi

npm install
