#!/bin/sh

# script/build: Compile the HTML and build the app to serve locally or deploy
#               via CI/CD.

set -e

UPDATE=true
CI=false

for ARG in "$@"
do
  case $ARG in
    --skip-update)
      UPDATE=false
      ;;
    --ci-environment)
      CI=true
      ;;
  esac
  shift
done

if [ "$UPDATE" = true ]; then
  if [ "$CI" = true ]; then
    script/update --ci-environment
  else
    script/update
  fi
fi

echo "==> Cleaning build directory"

rm -rf _site
mkdir _site

echo "==> Compiling HTML"

for VIEW_FILEPATH in views/*.html
do
  FILENAME=$(echo "$VIEW_FILEPATH" | awk '{print substr($0, 7)}')
  echo "Compiling _site/$FILENAME"
  cat views/layout/pre.html "$VIEW_FILEPATH" views/layout/post.html > "_site/$FILENAME"
done

echo "==> Copying admin config"

mkdir _site/admin

cp -r views/admin _site

echo "==> Formatting HTML"

bunx prettier --write _site/**/*.html

echo "==> Copying assets"

cp -r assets _site/assets

echo "==> Formatting CSS"

bunx stylelint --fix "_site/assets/styles/*.css"

echo "Completed build"
