#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

script/build

echo "==> Starting server and watching for file changes in assets and views"

(trap 'kill 0' SIGINT; npx http-server _site & (fswatch -or assets views | xargs -n1 -I{} script/build --skip-update))
