#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

CI=false

for ARG in "$@"
do
  case $ARG in
    --ci-environment)
      CI=true
      ;;
  esac
  shift
done

if [ "$CI" = true ]; then
  script/build --ci-environment
else
  script/build
fi


if [ "$CI" = true ]; then
  echo "==> Starting server"

  npx http-server _site
else
  echo "==> Starting server and watching for file changes in assets and views"

  (trap 'kill 0' SIGINT; npx http-server _site & (fswatch -or assets views | xargs -n1 -I{} script/build --skip-update))
fi
