#!/bin/sh

# script/update: Update the application to run for its current checkout.

set -e

CI=false

for ARG in "$@"
do
  case $ARG in
    --ci-environment)
      CI=true
      ;;
  esac
  shift
done

if [ "$CI" = true ]; then
  script/bootstrap --ci-environment
else
  script/bootstrap
fi
