name: Deploy

on:
  push:
    branches:
      - main

  # allow manual workflow run from actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# text from the GitHub action template:
#   Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
#   However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Build
        run: script/build --ci-environment
      - name: Set up Pages
        uses: actions/configure-pages@v3
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "_site"
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v2
