name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - End-to-end tests
    types:
      - completed
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

# text from the GitHub action template:
#   Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
#   However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Build
        run: script/build --ci-environment
      - name: Set up Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
        with:
          path: _site
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
